name: wellwait
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_svg: 0.22.0
  font_awesome_flutter: ^10.7.0
  google_fonts: 6.2.1
  image_picker: ^1.1.2
  intl_phone_field: ^3.2.0
  shared_preferences: ^2.3.2
  svg_icon: ^0.0.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    #  - assets/icons/notipic.png
